### ISSUE TITLE
!lb extremely innacurate even if its using avg.

### ISSUE THREAD

**Issue by HyxonQz** [aidn3/hypixel-guild-discord-bridge#47]
![image](https://user-images.githubusercontent.com/94485261/232332488-b5a418b5-6bfe-4b82-8549-40f50d9a30fd.png)
![image](https://user-images.githubusercontent.com/94485261/232332496-b35ab445-b2f6-44aa-9aa6-7517d9597e2f.png)

**Comment by HyxonQz** [comment]
This is with all items too

**Comment by aidn3** [comment]
Command removed in 0c812bb71cc71ba226aff1535d9b913acf7307ad.
The server that supplies the prices was acting and eventually went down.
