### ISSUE TITLE
Ingame guild mutes do not apply to discord bridges

### ISSUE THREAD

**Issue by HyxonQz** [aidn3/hypixel-guild-discord-bridge#49]
![image](https://user-images.githubusercontent.com/94485261/232336911-c9f312f1-42b9-45e1-8fe2-704fbac6bc4b.png)
![image](https://user-images.githubusercontent.com/94485261/232336915-7bc1413c-81d5-4044-9e25-693c0058098c.png)
![image](https://user-images.githubusercontent.com/94485261/232336919-f8716894-0312-410e-be63-d708f9e954bb.png)
![image](https://user-images.githubusercontent.com/94485261/232336928-3a2223ce-8c29-4632-9812-5ddcf2d75f05.png)
![Uploading image.png…]()
if someone is muted by staff ingame it does not apply to the whole bridge, allowing them to still talk via discord bridge channels

**Comment by aidn3** [comment]
Bug discovered. Mute only applies locally. Other instances across different nodes aren't receiving the notification via the websocket. Creating an event and transfer should fix the problem. This will be for the next upcoming major release

**Comment by aidn3** [comment]
solved per #156
