### ISSUE TITLE
Message repetition error when someone joins a guild

### ISSUE THREAD

**Issue by HyxonQz** [aidn3/hypixel-guild-discord-bridge#50]
![image](https://user-images.githubusercontent.com/94485261/232335229-e06f2db0-ec08-4ab2-bc8f-7e423f720f74.png)
Note: its not causes by people saying welcome, it errors without any messages being sent

**Comment by HyxonQz** [comment]
![](https://cdn.discordapp.com/attachments/1005978219733844050/1105625143558017034/IMG_3532.png)

**Comment by aidn3** [comment]
Can't reproduce. Probably bug went away at some point.
