### ISSUE TITLE
SUGGESTION - Auto accepter / denier

### ISSUE THREAD

**Issue by HyxonQz** [aidn3/hypixel-guild-discord-bridge#51]
when someone requests to join the guild, calculate the players networth and if it meets requirements, accept. else try to /msg them saying no and what the reqs are. also possibly a way to notify staff if the bot auto accepts / denies someone? perhaps a message in staff chat

**Comment by HyxonQz** [comment]
Also if the api is down, try to use skycrypt api cache but tell the user if they think it is incorrect to contact a staff member

**Comment by aidn3** [comment]
This is a very specific use case.

Commit 63b53f580a2a330863400d110469aacfb59fe740 and bbec992e52fe08fbebc15533e26ce5c5f819d888 should help creating a custom plugin with a custom notification.
