### ISSUE TITLE
/promote double trigger

### ISSUE THREAD

**Issue by HyxonQz** [aidn3/hypixel-guild-discord-bridge#59]

**Comment by HyxonQz** [comment]
![](https://cdn.discordapp.com/attachments/1005978219733844050/1105628912299548722/IMG_3533.png)

**Comment by aidn3** [comment]
I managed to replicate it.
So far, it only happens across different nodes. Maybe it has something to do with websockets.

**Comment by aidn3** [comment]
Further discoveries show that listeners are being registerred twice. One example is by reconnecting.
